# Use the official Python image as base
FROM python:3.10.9

# Install Streamlit
RUN pip install streamlit

# Copy your Streamlit app script into the container
COPY CYPUI.py /

# Expose port 8501 (Streamlit default port)
EXPOSE 8501

# Command to run the Streamlit app using the Streamlit CLI
CMD ["streamlit", "run", "--server.port", "8080", "CYPUI.py"]