# Use the official Python image as base
FROM python:3.10.9

# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit app script into the container
COPY CYPUI.py /app/

# Update pip and install Streamlit
RUN pip install --upgrade pip && \
    pip install streamlit

# Expose port 8501 for Streamlit
EXPOSE 8501

# Healthcheck to ensure Streamlit server is running
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Set the entrypoint to run the Streamlit app
ENTRYPOINT ["streamlit", "run", "CYPUI.py", "--server.port=8501", "--server.address=0.0.0.0"]
